todoProj/goals/urls.py
from django.urls import path
from . import views

app_name = 'goals'  # Important for URL namespacing

urlpatterns = [
    # goals
    path("", views.GoalListView.as_view(), name="list"),
    path("new/", views.GoalCreateView.as_view(), name="create_goal"),
    path("<int:pk>/", views.GoalDetailView.as_view(), name="goal_detail"),
    path("<int:pk>/edit/", views.GoalUpdateView.as_view(), name="goal_update"),
   
    # tasks 
    path("tasks/new/<int:goal_id>/", views.TaskCreateView.as_view(), name="task_create"),
    #path("tasks/new/<int:goal_id>/", views.TaskCreateView.as_view(), name="task_create"),
    #path("tasks/new/<int:goal_id>/", views.TaskCreateView.as_view(), name="task_create"),
    
    path("tasks/<int:pk>/edit/", views.TaskUpdateView.as_view(), name="task_update"),
    
    # --- Achievements ---
    path("achievements/", views.AchievementsView.as_view(), name="achievements"),
]
   

todoProj/todoProj/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    # path("accounts/", include("django.contrib.auth.urls")), 
    path('users/', include('users.urls')),
    path('goals/', include('goals.urls')),
]

todoProj/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout')
]

todoProj/users/models.py
from django.db import models

# Create your models here.

todoProj/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.
def register_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect("goals:list")
    else:
        form = UserCreationForm()
    return render(request, "users/register.html",{"form":form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():#LOGINHERE
            login(request, form.get_user())
            if "next" in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("goals:list")
    else:
        form = AuthenticationForm()
    return render(request, "users/login.html",{"form":form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("goals:list")

todoProj/users/templates/users/login.html
{%extends 'layout.html'%}

{% block title %}
    User Login
{% endblock %}

{% block content %}
    <h1> User Login </h1>
    <form class="container--top" action="{% url 'users:login' %}" method="post"> 
        {% csrf_token %}
        {{ form.as_p  }}
        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}"/>
        {% endif %}
        <button class="lime-sun-btn" type="submit"> Submit </button>
    </form>
{% endblock %}

todoProj/users/templates/users/register.html
{%extends 'layout.html'%}

{% block title %}
    Register a new User
{% endblock %}

{% block content %}
    <h1> Register a new User </h1>
    <form class="container--top" action="{% url 'users:register' %}" method="post"> 
        {% csrf_token %}
        {{ form.as_p }}
        <button class="lime-sun-btn" type="submit"> Submit </button>
    </form>
{% endblock %}